image:
  - quay.io/fedora/fedora-silverblue:latest
repositories:
	rpmfusion: True
	terra: True
	copr:
		- xxmitsu/mesa-git
packages:
	include:
		- python-pip
	exclude:
		- firefox
	local:
		#- 
modules:
	- virtualization
	- steam
services:
	autoupdates: True
    enable:
        - rpm-ostreed-automatic.service
