name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Parse YAML and prepare Dockerfile
      run: python3 build-script.py

    - name: Build the container image
      run: |
        docker build -t ghcr.io/emblem-66/custom-fedora:latest .

    - name: Push the container image
      run: |
        docker push ghcr.io/emblem-66/custom-fedora:latest
